# GET ALL USERS
GET http://localhost:5001/users
###

# GET A SINGLE USER
GET http://localhost:5001/users/2
###

# REGISTER A USER
POST http://localhost:5001/register
Content-Type: application/json

{
    "email": "brucewayne@gotham.com",
    "password": "test123"
}
###

# SIGN IN
POST http://localhost:5001/signin
Content-Type: application/json

{
    "email": "brucewayne@gmail.com",
    "password": "test123"
}

###

# GET ALL BOOKINGS
http://localhost:5001/bookings

###
# GET ALL BOOKINGS FOR A USER
http://localhost:5001/users/1/bookings
###
http://localhost:5001/listings

###


# POST http://localhost:5000/posts
# Content-Type: application/json

# {
#         "title": "airbnb clone",
#         "author": "puseletso"
#     }